import type {
  CalendarCheckResponse,
  CalendarPublishResponse,
  FutureEventItem,
  FutureEventsResponse,
  HideEventResponse,
  PaymentItem,
  PaymentsAnalyticsResponse,
  PaymentsListResponse,
} from "../api/types";

function nowIso(): string {
  return new Date().toISOString();
}

const demoEvents: FutureEventItem[] = [
  {
    message_id: 101,
    event_date: "2025-11-04",
    start_time: "19:30:00",
    end_time: "22:00:00",
    end_time_inferred: false,
    timezone: "Europe/London",
    event_type: "Theatre",
    event_name: "West End Premiere Night",
    calendar_event_id: null,
    calendar_checked_at: null,
    calendar_published_at: null,
    hidden_at: null,
    subject: "Your ticket confirmation",
    from_domain: "tickets.example.com",
    internal_date: "2025-10-18T12:40:00Z",
  },
  {
    message_id: 102,
    event_date: "2025-11-18",
    start_time: "18:00:00",
    end_time: "21:00:00",
    end_time_inferred: true,
    timezone: "America/New_York",
    event_type: "Comedy",
    event_name: "Stand-up Showcase",
    calendar_event_id: "demo-cal-102",
    calendar_checked_at: "2025-10-20T09:12:00Z",
    calendar_published_at: "2025-10-20T09:12:00Z",
    hidden_at: null,
    subject: "Your seats are confirmed",
    from_domain: "events.example.org",
    internal_date: "2025-10-20T08:03:00Z",
  },
  {
    message_id: 103,
    event_date: "2025-12-02",
    start_time: null,
    end_time: null,
    end_time_inferred: false,
    timezone: "Europe/London",
    event_type: "Social",
    event_name: "Holiday Networking Mixer",
    calendar_event_id: null,
    calendar_checked_at: "2025-10-24T14:00:00Z",
    calendar_published_at: null,
    hidden_at: null,
    subject: "RSVP confirmed",
    from_domain: "community.example.net",
    internal_date: "2025-10-23T11:02:00Z",
  },
  {
    message_id: 104,
    event_date: "2026-01-12",
    start_time: "20:00:00",
    end_time: "22:30:00",
    end_time_inferred: false,
    timezone: "Europe/London",
    event_type: "Cinema",
    event_name: "Indie Film Night",
    calendar_event_id: null,
    calendar_checked_at: null,
    calendar_published_at: null,
    hidden_at: "2025-11-01T10:00:00Z",
    subject: "Your cinema booking",
    from_domain: "cinema.example.co",
    internal_date: "2025-10-30T16:15:00Z",
  },
  {
    message_id: 105,
    event_date: "2026-02-05",
    start_time: "17:30:00",
    end_time: "20:00:00",
    end_time_inferred: false,
    timezone: "Europe/London",
    event_type: "Other",
    event_name: "Product Launch Night",
    calendar_event_id: null,
    calendar_checked_at: null,
    calendar_published_at: null,
    hidden_at: null,
    subject: "Your invite is confirmed",
    from_domain: "launch.example.io",
    internal_date: "2025-11-15T09:20:00Z",
  },
  {
    message_id: 106,
    event_date: "2026-02-22",
    start_time: "19:00:00",
    end_time: "21:00:00",
    end_time_inferred: false,
    timezone: "Europe/London",
    event_type: "Opera",
    event_name: "Winter Gala",
    calendar_event_id: "demo-cal-106",
    calendar_checked_at: "2025-11-21T18:01:00Z",
    calendar_published_at: "2025-11-21T18:01:00Z",
    hidden_at: null,
    subject: "Opera tickets secured",
    from_domain: "opera.example.org",
    internal_date: "2025-11-21T17:45:00Z",
  },
];

const demoPayments: PaymentItem[] = [
  {
    message_id: 201,
    item_name: "Cloud hosting subscription",
    vendor_name: "Cloudflare",
    item_category: "Technology",
    cost_amount: 84.99,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-11-01",
    payment_fingerprint: "demo-201",
    subject: "Your Cloudflare invoice",
    from_domain: "cloudflare.com",
    internal_date: "2025-11-01T08:01:00Z",
  },
  {
    message_id: 202,
    item_name: "Streaming subscription",
    vendor_name: "Netflix",
    item_category: "Entertainment",
    cost_amount: 17.49,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-11-03",
    payment_fingerprint: "demo-202",
    subject: "Netflix monthly receipt",
    from_domain: "netflix.com",
    internal_date: "2025-11-03T06:15:00Z",
  },
  {
    message_id: 203,
    item_name: "Conference ticket",
    vendor_name: "TechSummit",
    item_category: "Technology",
    cost_amount: 399.0,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-10-20",
    payment_fingerprint: "demo-203",
    subject: "TechSummit ticket confirmation",
    from_domain: "techsummit.example",
    internal_date: "2025-10-20T14:11:00Z",
  },
  {
    message_id: 204,
    item_name: "Grocery delivery",
    vendor_name: "FreshCart",
    item_category: "Food",
    cost_amount: 62.35,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-10-18",
    payment_fingerprint: "demo-204",
    subject: "FreshCart receipt",
    from_domain: "freshcart.example",
    internal_date: "2025-10-18T19:05:00Z",
  },
  {
    message_id: 205,
    item_name: "Water bill",
    vendor_name: "City Utilities",
    item_category: "Domestic Bills",
    cost_amount: 48.2,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-10-14",
    payment_fingerprint: "demo-205",
    subject: "Your water bill is ready",
    from_domain: "utilities.example.gov",
    internal_date: "2025-10-14T09:30:00Z",
  },
  {
    message_id: 206,
    item_name: "Gym membership",
    vendor_name: "Pulse Gym",
    item_category: "Lifestyle",
    cost_amount: 55.0,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-10-08",
    payment_fingerprint: "demo-206",
    subject: "Pulse Gym invoice",
    from_domain: "pulsegym.example",
    internal_date: "2025-10-08T07:20:00Z",
  },
  {
    message_id: 207,
    item_name: "Train tickets",
    vendor_name: "RailLink",
    item_category: "Other",
    cost_amount: 28.75,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-09-29",
    payment_fingerprint: "demo-207",
    subject: "Your RailLink booking",
    from_domain: "rail.example",
    internal_date: "2025-09-29T10:05:00Z",
  },
  {
    message_id: 208,
    item_name: "Streaming bundle",
    vendor_name: "Prime Video",
    item_category: "Entertainment",
    cost_amount: 12.99,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-09-25",
    payment_fingerprint: "demo-208",
    subject: "Prime Video receipt",
    from_domain: "primevideo.com",
    internal_date: "2025-09-25T08:45:00Z",
  },
  {
    message_id: 209,
    item_name: "Coffee subscription",
    vendor_name: "BeanDrop",
    item_category: "Food",
    cost_amount: 24.0,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-09-20",
    payment_fingerprint: "demo-209",
    subject: "BeanDrop monthly delivery",
    from_domain: "beandrop.example",
    internal_date: "2025-09-20T06:52:00Z",
  },
  {
    message_id: 210,
    item_name: "Smart home hub",
    vendor_name: "HomeBase",
    item_category: "Technology",
    cost_amount: 189.0,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-09-12",
    payment_fingerprint: "demo-210",
    subject: "Order confirmed",
    from_domain: "homebase.example",
    internal_date: "2025-09-12T13:40:00Z",
  },
  {
    message_id: 211,
    item_name: "Insurance premium",
    vendor_name: "SafeCover",
    item_category: "Domestic Bills",
    cost_amount: 92.3,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-08-28",
    payment_fingerprint: "demo-211",
    subject: "SafeCover premium receipt",
    from_domain: "safecover.example",
    internal_date: "2025-08-28T08:30:00Z",
  },
  {
    message_id: 212,
    item_name: "Concert tickets",
    vendor_name: "LiveNation",
    item_category: "Entertainment",
    cost_amount: 120.0,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-08-22",
    payment_fingerprint: "demo-212",
    subject: "Your tickets are ready",
    from_domain: "livenation.example",
    internal_date: "2025-08-22T17:25:00Z",
  },
  {
    message_id: 213,
    item_name: "Meal kit",
    vendor_name: "KitchenBox",
    item_category: "Food",
    cost_amount: 52.4,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-08-10",
    payment_fingerprint: "demo-213",
    subject: "KitchenBox receipt",
    from_domain: "kitchenbox.example",
    internal_date: "2025-08-10T18:10:00Z",
  },
  {
    message_id: 214,
    item_name: "Yoga workshop",
    vendor_name: "Serenity Studio",
    item_category: "Lifestyle",
    cost_amount: 36.0,
    cost_currency: "USD",
    is_recurring: false,
    frequency: null,
    payment_date: "2025-07-30",
    payment_fingerprint: "demo-214",
    subject: "Workshop confirmation",
    from_domain: "serenity.example",
    internal_date: "2025-07-30T09:12:00Z",
  },
  {
    message_id: 215,
    item_name: "Phone plan",
    vendor_name: "Telco",
    item_category: "Domestic Bills",
    cost_amount: 64.0,
    cost_currency: "USD",
    is_recurring: true,
    frequency: "monthly",
    payment_date: "2025-07-18",
    payment_fingerprint: "demo-215",
    subject: "Your Telco bill",
    from_domain: "telco.example",
    internal_date: "2025-07-18T07:45:00Z",
  },
];

export function demoGetFutureEvents(includeHidden: boolean): FutureEventsResponse {
  const events = includeHidden ? demoEvents : demoEvents.filter((e) => !e.hidden_at);
  return {
    generated_at: nowIso(),
    events,
  };
}

export function demoHideEvent(messageId: number): HideEventResponse {
  return {
    message_id: messageId,
    hidden: true,
    hidden_at: nowIso(),
  };
}

export function demoUnhideEvent(messageId: number): HideEventResponse {
  return {
    message_id: messageId,
    hidden: false,
    hidden_at: null,
  };
}

export function demoCheckEventCalendar(messageId: number): CalendarCheckResponse {
  return {
    message_id: messageId,
    calendar_ical_uid: `demo-${messageId}`,
    exists: false,
    calendar_event_id: null,
    calendar_checked_at: nowIso(),
  };
}

export function demoPublishEventCalendar(messageId: number): CalendarPublishResponse {
  return {
    message_id: messageId,
    calendar_ical_uid: `demo-${messageId}`,
    already_existed: false,
    calendar_event_id: `demo-cal-${messageId}`,
    calendar_published_at: nowIso(),
  };
}

export function demoGetPaymentsAnalytics(): PaymentsAnalyticsResponse {
  return {
    generated_at: nowIso(),
    window_start: "2025-07-01",
    window_end: "2026-01-24",
    currency: "USD",
    available_currencies: ["USD", "EUR"],
    payment_count: 42,
    total_spend: 1482.97,
    by_vendor: [
      { vendor: "Cloudflare", total_spend: 254.97 },
      { vendor: "Netflix", total_spend: 104.94 },
      { vendor: "TechSummit", total_spend: 399.0 },
      { vendor: "City Utilities", total_spend: 144.6 },
      { vendor: "Pulse Gym", total_spend: 165.0 },
    ],
    by_category: [
      { category: "Technology", total_spend: 842.96 },
      { category: "Entertainment", total_spend: 257.43 },
      { category: "Food", total_spend: 138.75 },
      { category: "Lifestyle", total_spend: 91.0 },
      { category: "Domestic Bills", total_spend: 153.83 },
      { category: "Other", total_spend: 40.0 },
    ],
    by_recurring: [
      { kind: "recurring", payment_count: 18, total_spend: 675.73 },
      { kind: "one_off", payment_count: 24, total_spend: 807.24 },
    ],
    by_frequency: [
      { frequency: "monthly", payment_count: 18, total_spend: 675.73 },
    ],
    by_month: [
      { month: "2025-07-01", payment_count: 6, total_spend: 214.4 },
      { month: "2025-08-01", payment_count: 7, total_spend: 351.7 },
      { month: "2025-09-01", payment_count: 8, total_spend: 380.73 },
      { month: "2025-10-01", payment_count: 10, total_spend: 353.04 },
      { month: "2025-11-01", payment_count: 11, total_spend: 183.1 },
    ],
  };
}

export function demoGetPaymentsRecent(limit: number): PaymentsListResponse {
  const payments = demoPayments.slice(0, Math.max(0, limit));
  return {
    generated_at: nowIso(),
    payments,
  };
}
